// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230610083908_Seeding data to DB")]
    partial class SeedingdatatoDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("employeeCount")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("_id");

                    b.ToTable("Companys");

                    b.HasData(
                        new
                        {
                            id = "c9d4c053-49b6-410c-bc78-2d54a9991870",
                            address = "Some place near neptune",
                            employeeCount = 1451,
                            name = "SamDev Solutions"
                        },
                        new
                        {
                            id = "3d490a70-94ce-4d15-9494-5248280c2ce3",
                            address = "Some place mysterious place near the outer galaxy",
                            employeeCount = 123456,
                            name = "Radio Shack"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
